import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CoinStamp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page-container flex min-h-[70vh] flex-col items-center justify-center space-y-5">
        <h1 className="text-6xl font-bold">CoinStamp</h1>
        <p>Use decentralized currencies to buy and print your postage.</p>
        <div>
          <button className="btn btn-primary">Get Started</button>
          <button className="btn btn-secondary">Read More</button>
        </div>
      </main>
    </>
  );
};

export default Home;
